trigger:
  - main

variables:
  azureServiceConnection: "k8reemsAZConnection"
  resourceGroupName: "resume-rg"
  storageAccountName: "resumeweba492c275"

stages:
  - stage: Deploy
    displayName: "Deploy Resume"
    pool:
      vmImage: 'ubuntu-latest'  # or 'windows-latest' if preferred
    jobs:
      - job: Deploy
        steps:
          - task: AzureFileCopy@4
            displayName: "Upload Resume Files"
            inputs:
              SourcePath: "$(System.DefaultWorkingDirectory)/resume-files"
              azureSubscription: $(azureServiceConnection)
              Destination: "AzureBlob"
              storage: $(storageAccountName)
              ContainerName: "$web"
